#!/bin/bash
# Hugging Face Spaces Deployment Instructions
# ============================================

echo "🤗 Deploying Stock Prediction API to Hugging Face Spaces"
echo ""
echo "Due to network restrictions in this environment, please follow these steps:"
echo ""
echo "OPTION 1: Direct Web Upload (Easiest)"
echo "======================================"
echo "1. Go to your existing space: https://huggingface.co/spaces/iofocus/stocks_price_prediction"
echo ""
echo "2. Click 'Files and versions' > 'Add file' > 'Upload files'"
echo ""
echo "3. Upload these 4 files from /home/user/Stock-path:"
echo "   - README.md"
echo "   - requirements.txt"
echo "   - Dockerfile"
echo "   - app.py"
echo ""
echo "4. Click 'Commit changes to main'"
echo ""
echo "Your space will build automatically and be ready in 5-10 minutes!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "OPTION 2: Git Push (Advanced)"
echo "=============================="
echo "1. Create space at: https://huggingface.co/new-space"
echo "   - Name: stock-prediction-api"
echo "   - SDK: Docker"
echo ""
echo "2. Clone your space locally:"
echo "   git clone https://huggingface.co/spaces/iofocus/stocks_price_prediction"
echo "   cd stocks_price_prediction"
echo ""
echo "3. Copy files:"
echo "   cp /home/user/Stock-path/README.md ."
echo "   cp /home/user/Stock-path/requirements.txt ."
echo "   cp /home/user/Stock-path/Dockerfile ."
echo "   cp /home/user/Stock-path/app.py ."
echo ""
echo "4. Set up git credentials:"
echo "   git config credential.helper store"
echo "   echo 'https://iofocus:YOUR_HF_TOKEN@huggingface.co' > ~/.git-credentials"
echo "   # Replace YOUR_HF_TOKEN with your actual token"
echo ""
echo "5. Commit and push:"
echo "   git add ."
echo "   git commit -m 'Initial deployment of Stock Prediction API'"
echo "   git push"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📦 All required files are ready in: /home/user/Stock-path"
echo ""
echo "Your API will be available at:"
echo "  🌐 https://iofocus-stocks-price-prediction.hf.space"
echo "  📚 API Docs: https://iofocus-stocks-price-prediction.hf.space/docs"
echo "  🔗 Example: https://iofocus-stocks-price-prediction.hf.space/api/predict/AAPL"
